#!/bin/bash

if [ $# -lt 2 ]; then
  echo "usage: count FIRST LAST DIGITS STEP"
  exit -1
fi

FIRST=$1
LAST=$2
DIG=$3
STEP=$4
NUM=$FIRST

while [ $NUM -le $LAST ]; do
  D=2
  N=10
  STR=$NUM
  while [ $D -le $DIG ]; do
    if [ $NUM -lt $N ]; then
      STR=0$STR
    fi    
    N=$[ $N * 10 ];
    D=$[ $D + 1 ];
  done
  echo -n $STR
  NUM=$[ $NUM + $STEP ];
  echo -n " "
done
