#!/bin/sh
if [ $# -ne 2 ]; then
  echo "Usage:"
  echo "  gendiff DIRECTORY SUFFIX"
  echo ""
  echo "Example:"
  echo "  gendiff ./ .BAK"
  exit
fi

DIR=$1
SUFFIX=$2

for I in `find $DIR -name "*"$SUFFIX -print`; do
  F=`echo -n $I | sed s/$SUFFIX//`;
  diff -u $I $F
done
