#!/bin/sh

mke2fs -j -L "Media" -O sparse_super -T largefile /dev/$1
tune2fs -c 0 /dev/$1
pmount /dev/$1
mkdir /media/$1/Videos
mkdir /media/$1/Photos
mkdir /media/$1/Music
mkdir /media/$1/Miscellaneous
chmod a+r+w /media/$1/*
chmod a+r+w /media/$1
pumount /dev/$1
