#!/bin/sh

# DEFAULTS

# Output file
OUTPUT="DVD.avi"
# Good Quality: 11.75 Mb/min
BITRATE=1800
DATARATE=12032

if [ "$1" = "-h" ]; then
  echo "Arguments:"
  echo "   "$0" Input_file Output_File.avi [datarate in Kb/min]]"
  echo ""
  echo "    Default output:   "$OUTPUT
  echo "    Default datarate: "$DATARATE" Kb/min"
  exit -1
fi

if [ $# -gt 1 ]; then
  INPUT=$1
  OUTPUT=$2
fi

if [ $# -gt 2 ]; then
  DATARATE=$3
  BITRATE=$[ $DATARATE * 10000 / 66844 ];
fi

echo "Output:   "$OUTPUT
echo "Datarate: "$DATARATE" Kb/min"
echo "Bitrate:  "$BITRATE
echo "--------------------------------------------------------------------------------"
sleep 5
transcode \
-i $INPUT \
-V \
-y divx5 \
-w $BITRATE \
-b 96 \
-Z 720x400 \
--no_split \
-o $OUTPUT
rm -f c:\\trace_b.txt
